services:
    importdefinitions.coreshop.interpreter.price:
        class: ImportDefinitionsBundle\Interpreter\CoreShop\PriceInterpreter
        tags:
            - { name: import_definition.interpreter, type: coreshop_price, form-type: ImportDefinitionsBundle\Form\Type\Interpreter\CoreShop\PriceInterpreterType }

    importdefinitions.coreshop.setter.store_price:
        class: ImportDefinitionsBundle\Setter\CoreShop\StorePriceSetter
        arguments:
            - '@coreshop.repository.store'
        tags:
            - { name: import_definition.setter, type: coreshop_store_price, form-type: ImportDefinitionsBundle\Form\Type\Setter\CoreShop\StorePriceSetterType }

    importdefinitions.coreshop.interpreter.stores:
        class: ImportDefinitionsBundle\Interpreter\CoreShop\StoresInterpreter
        tags:
            - { name: import_definition.interpreter, type: coreshop_stores, form-type: ImportDefinitionsBundle\Form\Type\Interpreter\CoreShop\StoresInterpreterType }

    importdefinitions.coreshop.interpreter.currency:
        class: ImportDefinitionsBundle\Interpreter\CoreShop\CurrencyInterpreter
        arguments:
            - '@coreshop.repository.currency'
        tags:
            - { name: import_definition.interpreter, type: coreshop_currency, form-type: ImportDefinitionsBundle\Form\Type\NoConfigurationType }