jms_serializer:
    metadata:
        directories:
            import-definitions:
                namespace_prefix: "ImportDefinitionsBundle"
                path: "@ImportDefinitionsBundle/Resources/config/serializer"

import_definitions:
    pimcore_admin:
        js:
            startup: '/bundles/importdefinitions/pimcore/js/startup.js'
            definition_abstract_item: '/bundles/importdefinitions/pimcore/js/definition/abstractItem.js'
            import_definition_panel: '/bundles/importdefinitions/pimcore/js/import/panel.js'
            import_definition_item: '/bundles/importdefinitions/pimcore/js/import/item.js'
            import_definition_config: '/bundles/importdefinitions/pimcore/js/import/configDialog.js'
            export_definition_panel: '/bundles/importdefinitions/pimcore/js/export/panel.js'
            export_definition_item: '/bundles/importdefinitions/pimcore/js/export/item.js'
            export_definition_config: '/bundles/importdefinitions/pimcore/js/export/configDialog.js'
            export_definition_fields: '/bundles/importdefinitions/pimcore/js/export/fields.js'
            import_provider_abstract: '/bundles/importdefinitions/pimcore/js/provider/abstractprovider.js'
            import_provider_csv: '/bundles/importdefinitions/pimcore/js/provider/csv.js'
            import_provider_excel: '/bundles/importdefinitions/pimcore/js/provider/excel.js'
            import_provider_sql: '/bundles/importdefinitions/pimcore/js/provider/sql.js'
            import_provider_external_sql: '/bundles/importdefinitions/pimcore/js/provider/externalSql.js'
            import_provider_json: '/bundles/importdefinitions/pimcore/js/provider/json.js'
            import_provider_xml: '/bundles/importdefinitions/pimcore/js/provider/xml.js'
            import_provider_raw: '/bundles/importdefinitions/pimcore/js/provider/raw.js'
            export_provider_abstract: '/bundles/importdefinitions/pimcore/js/export_provider/abstractprovider.js'
            export_provider_csv: '/bundles/importdefinitions/pimcore/js/export_provider/csv.js'
            export_provider_xml: '/bundles/importdefinitions/pimcore/js/export_provider/xml.js'
            resource_definition: '/bundles/importdefinitions/pimcore/js/resource/definition.js'
            definition_panel: '/bundles/importdefinitions/pimcore/js/import/panel.js'
            definition_item: '/bundles/importdefinitions/pimcore/js/import/item.js'
            definition_config: '/bundles/importdefinitions/pimcore/js/import/configDialog.js'
            interpreter_abstract: '/bundles/importdefinitions/pimcore/js/interpreters/abstract.js'
            interpreter_href: '/bundles/importdefinitions/pimcore/js/interpreters/href.js'
            interpreter_multihref: '/bundles/importdefinitions/pimcore/js/interpreters/multihref.js'
            interpreter_defaultvalue: '/bundles/importdefinitions/pimcore/js/interpreters/defaultvalue.js'
            interpreter_specificobject: '/bundles/importdefinitions/pimcore/js/interpreters/specificobject.js'
            interpreter_assetbypath: '/bundles/importdefinitions/pimcore/js/interpreters/assetbypath.js'
            interpreter_asseturl: '/bundles/importdefinitions/pimcore/js/interpreters/asseturl.js'
            interpreter_assetsurl: '/bundles/importdefinitions/pimcore/js/interpreters/assetsurl.js'
            interpreter_quantityvalue: '/bundles/importdefinitions/pimcore/js/interpreters/quantityvalue.js'
            interpreter_nested: '/bundles/importdefinitions/pimcore/js/interpreters/nested.js'
            interpreter_nested_container: '/bundles/importdefinitions/pimcore/js/interpreters/nestedcontainer.js'
            interpreter_empty: '/bundles/importdefinitions/pimcore/js/interpreters/empty.js'
            interpreter_expression: '/bundles/importdefinitions/pimcore/js/interpreters/expression.js'
            interpreter_object_resolver: '/bundles/importdefinitions/pimcore/js/interpreters/objectresolver.js'
            interpreter_mapping: '/bundles/importdefinitions/pimcore/js/interpreters/mapping.js'
            interpreter_iterator: '/bundles/importdefinitions/pimcore/js/interpreters/iterator.js'
            interpreter_definition: '/bundles/importdefinitions/pimcore/js/interpreters/definition.js'
            interpreter_conditional: '/bundles/importdefinitions/pimcore/js/interpreters/conditional.js'
            interpreter_twig: '/bundles/importdefinitions/pimcore/js/interpreters/twig.js'
            setter_abstract: '/bundles/importdefinitions/pimcore/js/setters/abstract.js'
            setter_fieldcollection: '/bundles/importdefinitions/pimcore/js/setters/fieldcollection.js'
            setter_objectbrick: '/bundles/importdefinitions/pimcore/js/setters/objectbrick.js'
            setter_classificationstore: '/bundles/importdefinitions/pimcore/js/setters/classificationstore.js'
            setter_localizedfield: '/bundles/importdefinitions/pimcore/js/setters/localizedfield.js'
            getter_fieldcollection: '/bundles/importdefinitions/pimcore/js/getters/fieldcollection.js'
            getter_objectbrick: '/bundles/importdefinitions/pimcore/js/getters/objectbrick.js'
            getter_classificationstore: '/bundles/importdefinitions/pimcore/js/getters/classificationstore.js'
            getter_localizedfield: '/bundles/importdefinitions/pimcore/js/getters/localizedfield.js'
            fetcher_abstract: '/bundles/importdefinitions/pimcore/js/fetchers/abstract.js'
            fetcher_objects: '/bundles/importdefinitions/pimcore/js/fetchers/objects.js'
        css:
            import_definition: '/bundles/importdefinitions/pimcore/css/importdefinition.css'
